import Footer from '@/components/footer';
import Navbar from '@/components/navbar';
import './globals.css';

export const metadata = {
	title: 'Mathive',
	description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<body>
				<Navbar />
				{children}
				<Footer />
			</body>
		</html>
	);
}
